apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer # This tells Docker Desktop to give you a "real" IP/Port on your machine
  selector:
    app: fastapi-web # This MUST match the label in your Deployment
  ports:
    - protocol: TCP
      port: 8080      # The port you will type in your browser (localhost:8080)
      targetPort: 80  # The port the container is listening on inside the pod
