name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Trigger this when you push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # GitHub will provide a free Linux server to run this

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # We need to set this in GitHub
        password: ${{ secrets.DOCKER_PASSWORD }} # We need to set this in GitHub

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: rexx0924/my-fastapi-app:latest,rexx0924/my-fastapi-app:${{ github.sha }} # Tag with 'latest' AND the commit hash
